### ISSUE TITLE
RuntimeError at processing time: Sizes of tensors after decoder do not match

### ISSUE THREAD

**Issue by adriaat** [SEE-GEO/ccic#28]
When processing some files, e.g.
```
$ ccic process /mnt/data_copper2/ccic/models/ccic_v2.pckl cpcir ~/tmp 2018-08-19T17:30:00 --roi -156 12.9 -143.4 20
```
the following error is raised:
```
/home/amell/ccic/ccic/bin/process.py (ERROR     ) :: Sizes of tensors must match except in dimension 1. Expected size 21 but got size 20 for tensor number 1 in the list.
Traceback (most recent call last):
  File "/home/amell/ccic/ccic/bin/process.py", line 178, in process_files
    results = process_input_file(
  File "/home/amell/ccic/ccic/processing.py", line 634, in process_input_file
    results = process_input(
  File "/home/amell/ccic/ccic/processing.py", line 543, in process_input
    y_pred = mrnn.predict(x_t)
  File "/home/amell/quantnn/quantnn/mrnn.py", line 730, in predict
    self.model.predict(x),
  File "/home/amell/quantnn/quantnn/models/pytorch/common.py", line 982, in predict
    y = self(x_torch)
  File "/home/amell/miniconda3/envs/ccic/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/amell/ccic/ccic/models.py", line 101, in forward
    y = self.decoder(y)
  File "/home/amell/miniconda3/envs/ccic/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/amell/quantnn/quantnn/models/pytorch/decoders.py", line 166, in forward
    y = stage(torch.cat([x_skip, up(y)], dim=1))
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 21 but got size 20 for tensor number 1 in the list.
```

**Comment by simonpf** [comment]
So a quick fix is to specify the tile size to be 256 using ``--tile_size 256``. I will look into a way of handling this properly.
