### ISSUE TITLE
CPCIR-Alvis: (some) jobs are not terminating until time limit is reached

### ISSUE THREAD

**Issue by adriaat** [SEE-GEO/ccic#67]
The current jobs I am submitting to Alvis to process CPCIR can experience the following: processing completed, but the job does not finish, so it keeps the resources unavailable for further processing or other users until the time cap is reached. The stats below show an example:

![stats dashboard](https://github.com/SEE-GEO/ccic/assets/28195522/205ec7e7-dc87-4b5a-bf57-a2b2255a3aa8)

(That the GPU memory usage is this low is related to how the job script is organized and that I was processing `--failed` files. When processing 'a first pass' the memory usage is very high.)

I think there might be some 'ghost' processes running preventing the job to terminate, particularly because there is a small bump in memory usage around 09:45 without an increase in CPU in the example shared.

I need to highlight that, while I detected this to happen usually, I also saw this to not happen...

Since this issue keeps the resources busy but unused, I halted the processing of CPCIR until this is resolved.

**Comment by adriaat** [comment]
I tried doing processing offline in the cluster (code not pushed to the GitHub main repo, but in a fork [here](https://github.com/adriaat/ccic/tree/offline)). The same scripts did not suffer and did suffer this issue. Therefore it can be difficult to identify what is causing this issue, but at least that it's something depending only on "the Internet connection" can, in principle, be ruled out.

**Comment by adriaat** [comment]
Replying to my question above: I should probably have noticed the use of a [lock](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.Lock), introduced as a hard-coded value with 9fb0aa49541358eeefa7c23d0a501b8e73408663, which prevents the GPU to execute more than one prediction simultaneously, even if `--n_processes` is greater than 1. I don't remember why this was introduced, but maybe to avoid CUDA OOMs?

Since there's a new higher time limit in the cluster, I re-wrote the slurm bash scripts making use of it as well as not imposing a GPU device lock (i.e. [ccic.bin.process.py:533](https://github.com/SEE-GEO/ccic/blob/055ede0e61238a35801662d9f024b7f3019e0c79/ccic/bin/process.py#L533) set to `None`), and running with `--n_processes 3`.

For now it seems to work, but this needs to be run for a while to detect if this solves the issue. However, in the meantime, we get more files processed without underusing the resources (currently, the average GPU usage is almost 100%, with 54% GPU mem used).

**Comment by adriaat** [comment]
Related, to not open a new issue at the moment.
The processing can halt with neither any processing happening nor the job terminating if, for any reason, an input file is present in the `--input_path` but this file cannot be opened, i.e. it is corrupt. The following is the error message:
```
[ERROR] (ccic.bin.process): Downloading of input file 'merg_2016010102_4km-pixel.nc4' failed.
Traceback (most recent call last):
  File "/opt/conda/envs/ccic/lib/python3.10/site-packages/ccic/bin/process.py", line 319, in download_files
    input_file, clean_up = input_file.get()
  File "/opt/conda/envs/ccic/lib/python3.10/site-packages/ccic/processing.py", line 107, in get
    return self.file_cls(output_path), False
  File "/opt/conda/envs/ccic/lib/python3.10/site-packages/ccic/data/cpcir.py", line 243, in __init__
    with xr.open_dataset(self.filename) as data:
  File "/opt/conda/envs/ccic/lib/python3.10/site-packages/xarray/backends/api.py", line 553, in open_dataset
    engine = plugins.guess_engine(filename_or_obj)
  File "/opt/conda/envs/ccic/lib/python3.10/site-packages/xarray/backends/plugins.py", line 197, in guess_engine
    raise ValueError(error_msg)
ValueError: did not find a match in any of xarray's currently installed IO backends ['netcdf4', 'scipy', 'gini', 'zarr']. Consider explicitly selecting one of the installed engines via the ``engine`` parameter, or installing additional IO dependencies, see:
https://docs.xarray.dev/en/stable/getting-started-guide/installing.html
https://docs.xarray.dev/en/stable/user-guide/io.html
Exception in thread Thread-1 (download_files):
Traceback (most recent call last):
  File "/opt/conda/envs/ccic/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/ccic/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/ccic/lib/python3.10/site-packages/ccic/bin/process.py", line 325, in download_files
    processing_queue.put((input_file, clean_up))
UnboundLocalError: local variable 'clean_up' referenced before assignment
```

**Comment by adriaat** [comment]
The processing of CPCIR is moving forward, but using the hack from https://github.com/SEE-GEO/ccic/issues/67#issuecomment-1883218373 is not solving the issue, below an example:
![image](https://github.com/SEE-GEO/ccic/assets/28195522/e1eeaa0d-6b0d-4823-9ee0-075fe9ababa0)
The job has completed the processing of all files it had to process, I have not identified any warning or error in the logs, but the job does terminate; it's consuming a considerably large amount of memory.

I think there is definitely something happening with the way we have structured the code that causes this to not exit nicely, and it's difficult to asses what is it in a non-interactive setup such as the cluster.

It is probably related the step behaviour in the memory that is seen in the previous screenshot as well as in the one below (which will end up in an OOM if it takes one more step):
![image](https://github.com/SEE-GEO/ccic/assets/28195522/8f9f8135-4ce5-45f4-966a-0a038a18342a).

I honestly have no idea what can be causing this issue (looks like a memory leak or zombie processes). Instead of spending more time trying to fix this, I think I prefer to spend some time "babysitting" the cluster process and killing them manually, if needed.

**Comment by adriaat** [comment]
Logging a bit more information:
Perhaps the large amount of memory is not an issue. I 'read online' (I lack the source now to reference it) that this consistent increase in memory can be normal when working with large datasets and it might be due to how Python-the OS manage the memory space. Below screenshots of three jobs that have been running for almost 4 days now:

![1771122](https://github.com/SEE-GEO/ccic/assets/28195522/be66f009-b422-49e2-9fa5-90a31c7376f3)

![1771123](https://github.com/SEE-GEO/ccic/assets/28195522/bfd0dede-98a8-42a7-b61e-a6e1b15a857e)

![1771124](https://github.com/SEE-GEO/ccic/assets/28195522/4cb4d37c-35e6-439c-a845-5299b3543081)

Looks like the system is smart: no 'Killed.' messages in the logs or any other error related to this memory consumption near the edge.

**Comment by simonpf** [comment]
I had a look at the code and suspect that this  [this line](https://github.com/SEE-GEO/ccic/blob/7323ed63d2c9be421550eb7c524052e5d0761f36/ccic/bin/process.py#L332) can cause a race condition which may cause the download thread to not terminate. Can you try removing this line and see if the problem persists?

**Comment by adriaat** [comment]
Thanks for the hint. I have removed this line and I am trying it.

**Comment by adriaat** [comment]
Removing that LOC seems promising. Three jobs that terminated finished as they should. We need to wait more, though.

**Comment by adriaat** [comment]
And we waited more and removing that LOC does not *completely* solve the issue, at least for one job 1783582, but during this job 301 files failed to download!

I still think though that was an improvement, so it should end up in main.

**Comment by adriaat** [comment]
Update: after all CPCIR data for 1998-2023 has been processed, I confirm that removing the suggested LOC (in #87) does not completely solve the issue but it seems to mitigate it; there were less idle jobs when removing this LOC. It cannot be ruled out that the root of the problem is somewhere else.

**Comment by adriaat** [comment]
Perhaps related: the multiprocessing start context may be preventing a proper memory cleanup. It doesn't play nicely when there are GPU involved. I came across this in another work.
